package jpa;
// Generated 28-nov-2019 14:02:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name = "doctor", schema = "public")
public class DoctorJPA implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private String nif;
	private String name;
	private String surname;
	private String password;
	private String email;
	private Set<FamilydoctorJPA> familydoctors = new HashSet<FamilydoctorJPA>(0);
	private Set<SpecialistdoctorJPA> specialistdoctors = new HashSet<SpecialistdoctorJPA>(0);

	public DoctorJPA() {
	}

	public DoctorJPA(long id, String nif, String name, String surname, String password, String email) {
		this.id = id;
		this.nif = nif;
		this.name = name;
		this.surname = surname;
		this.password = password;
		this.email = email;
	}

	public DoctorJPA(long id, String nif, String name, String surname, String password, String email,
			Set<FamilydoctorJPA> familydoctors, Set<SpecialistdoctorJPA> specialistdoctors) {
		this.id = id;
		this.nif = nif;
		this.name = name;
		this.surname = surname;
		this.password = password;
		this.email = email;
		this.familydoctors = familydoctors;
		this.specialistdoctors = specialistdoctors;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "nif", nullable = false, length = 9)
	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "surname", nullable = false, length = 100)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Column(name = "password", nullable = false, length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", nullable = false, length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "doctor")
	public Set<FamilydoctorJPA> getFamilydoctors() {
		return this.familydoctors;
	}

	public void setFamilydoctors(Set<FamilydoctorJPA> familydoctors) {
		this.familydoctors = familydoctors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "doctor")
	public Set<SpecialistdoctorJPA> getSpecialistdoctors() {
		return this.specialistdoctors;
	}

	public void setSpecialistdoctors(Set<SpecialistdoctorJPA> specialistdoctors) {
		this.specialistdoctors = specialistdoctors;
	}

}
