package jpa;
// Generated 28-nov-2019 14:02:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Familydoctor generated by hbm2java
 */
@Entity
@Table(name = "familydoctor", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "doctor_id"))
public class FamilydoctorJPA implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private double id;
	private DoctorJPA doctor;
	private PrimaryhealthcarecenterJPA primaryhealthcarecenter;
	private Set<VisitJPA> visits = new HashSet<VisitJPA>(0);
	private Set<PatientJPA> patients = new HashSet<PatientJPA>(0);

	public FamilydoctorJPA() {
	}

	public FamilydoctorJPA(double id, DoctorJPA doctor, PrimaryhealthcarecenterJPA primaryhealthcarecenter) {
		this.id = id;
		this.doctor = doctor;
		this.primaryhealthcarecenter = primaryhealthcarecenter;
	}

	public FamilydoctorJPA(double id, DoctorJPA doctor, PrimaryhealthcarecenterJPA primaryhealthcarecenter, Set<VisitJPA> visits,
			Set<PatientJPA> patients) {
		this.id = id;
		this.doctor = doctor;
		this.primaryhealthcarecenter = primaryhealthcarecenter;
		this.visits = visits;
		this.patients = patients;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, precision = 17, scale = 17)
	public double getId() {
		return this.id;
	}

	public void setId(double id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doctor_id", unique = true, nullable = false)
	public DoctorJPA getDoctor() {
		return this.doctor;
	}

	public void setDoctor(DoctorJPA doctor) {
		this.doctor = doctor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "primaryhealthcarecenter_id", nullable = false)
	public PrimaryhealthcarecenterJPA getPrimaryhealthcarecenter() {
		return this.primaryhealthcarecenter;
	}

	public void setPrimaryhealthcarecenter(PrimaryhealthcarecenterJPA primaryhealthcarecenter) {
		this.primaryhealthcarecenter = primaryhealthcarecenter;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "familydoctor")
	public Set<VisitJPA> getVisits() {
		return this.visits;
	}

	public void setVisits(Set<VisitJPA> visits) {
		this.visits = visits;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "familydoctor")
	public Set<PatientJPA> getPatients() {
		return this.patients;
	}

	public void setPatients(Set<PatientJPA> patients) {
		this.patients = patients;
	}

}
