package jpa;
// Generated 28-nov-2019 14:02:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Medicalspecialty generated by hbm2java
 */
@Entity
@Table(name = "medicalspecialty", schema = "public")
public class MedicalspecialtyJPA implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private String name;
	private String description;
	private Set<SpecialistdoctorJPA> specialistdoctors = new HashSet<SpecialistdoctorJPA>(0);

	public MedicalspecialtyJPA() {
	}

	public MedicalspecialtyJPA(long id, String name, String description) {
		this.id = id;
		this.name = name;
		this.description = description;
	}

	public MedicalspecialtyJPA(long id, String name, String description, Set<SpecialistdoctorJPA> specialistdoctors) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.specialistdoctors = specialistdoctors;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medicalspecialty")
	public Set<SpecialistdoctorJPA> getSpecialistdoctors() {
		return this.specialistdoctors;
	}

	public void setSpecialistdoctors(Set<SpecialistdoctorJPA> specialistdoctors) {
		this.specialistdoctors = specialistdoctors;
	}

}
