package jpa;
// Generated 28-nov-2019 14:02:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Primaryhealthcarecenter generated by hbm2java
 */
@Entity
@Table(name = "primaryhealthcarecenter", schema = "public")
public class PrimaryhealthcarecenterJPA implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private String name;
	private String location;
	private Set<FamilydoctorJPA> familydoctors = new HashSet<FamilydoctorJPA>(0);

	public PrimaryhealthcarecenterJPA() {
	}

	public PrimaryhealthcarecenterJPA(long id, String name, String location) {
		this.id = id;
		this.name = name;
		this.location = location;
	}

	public PrimaryhealthcarecenterJPA(long id, String name, String location, Set<FamilydoctorJPA> familydoctors) {
		this.id = id;
		this.name = name;
		this.location = location;
		this.familydoctors = familydoctors;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "location", nullable = false, length = 500)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "primaryhealthcarecenter")
	public Set<FamilydoctorJPA> getFamilydoctors() {
		return this.familydoctors;
	}

	public void setFamilydoctors(Set<FamilydoctorJPA> familydoctors) {
		this.familydoctors = familydoctors;
	}

}
