package jpa;
// Generated 28-nov-2019 14:02:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Testtype generated by hbm2java
 */
@Entity
@Table(name = "testtype", schema = "public")
public class TesttypeJPA implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private String description;
	private Set<MedicaltestJPA> medicaltests = new HashSet<MedicaltestJPA>(0);

	public TesttypeJPA() {
	}

	public TesttypeJPA(long id, String description) {
		this.id = id;
		this.description = description;
	}

	public TesttypeJPA(long id, String description, Set<MedicaltestJPA> medicaltests) {
		this.id = id;
		this.description = description;
		this.medicaltests = medicaltests;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "description", nullable = false, length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "testtype")
	public Set<MedicaltestJPA> getMedicaltests() {
		return this.medicaltests;
	}

	public void setMedicaltests(Set<MedicaltestJPA> medicaltests) {
		this.medicaltests = medicaltests;
	}

}
