package jpa;
// Generated 28-nov-2019 14:02:34 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Visit generated by hbm2java
 */
@Entity
@Table(name = "visit", schema = "public")
public class VisitJPA implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private FamilydoctorJPA familydoctor;
	private PatientJPA patient;
	private Date date;
	private Date time;
	private String observations;
	private String result;

	public VisitJPA() {
	}

	public VisitJPA(long id, FamilydoctorJPA familydoctor, PatientJPA patient, Date date, Date time) {
		this.id = id;
		this.familydoctor = familydoctor;
		this.patient = patient;
		this.date = date;
		this.time = time;
	}

	public VisitJPA(long id, FamilydoctorJPA familydoctor, PatientJPA patient, Date date, Date time, String observations,
			String result) {
		this.id = id;
		this.familydoctor = familydoctor;
		this.patient = patient;
		this.date = date;
		this.time = time;
		this.observations = observations;
		this.result = result;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "familydoctor_id", nullable = false)
	public FamilydoctorJPA getFamilydoctor() {
		return this.familydoctor;
	}

	public void setFamilydoctor(FamilydoctorJPA familydoctor) {
		this.familydoctor = familydoctor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patient_id", nullable = false)
	public PatientJPA getPatient() {
		return this.patient;
	}

	public void setPatient(PatientJPA patient) {
		this.patient = patient;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 22)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", nullable = false, length = 22)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "observations", length = 2000)
	public String getObservations() {
		return this.observations;
	}

	public void setObservations(String observations) {
		this.observations = observations;
	}

	@Column(name = "result", length = 200)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

}
